Update README.md
jadijadi/gittutorial pull request #436
Opened 2021-08-02 13:15 UTC by kiumad

2021-08-02 13:15 UTC, kiumad commented
❤️

2021-08-04 07:13 UTC, dornam requested changes

2021-08-04 07:13 UTC, dornam commented on README.md
> +- [Seyed mohammad mirfatemi :speech_balloon:](https://github.com/kiumad)
[Dorna :grin: :sunglasses:] (https:\\gits.github.com\dornam)

2021-08-04 07:19 UTC, kiumad commented on README.md
> +- [Seyed mohammad mirfatemi :speech_balloon:](https://github.com/kiumad)
😁

2021-08-05 14:46 UTC, merged